import { pgTable, text, timestamp, uuid, numeric, integer, pgEnum } from 'drizzle-orm/pg-core';
import { relations, sql } from 'drizzle-orm';
import { customersTable } from './customer';
import { productVariantsTable } from './catalogue';
import { discountCodesTable } from './discount';

// Cart status enum
export const cartStatusEnum = pgEnum('cart_status', [
  'active',      // Cart in use
  'abandoned',   // Inactive for X days
  'converted',   // Successfully checked out
  'merged'       // Guest cart merged into user cart
]);

// Carts table
export const cartsTable = pgTable('carts', {
  id: uuid('id').defaultRandom().primaryKey(),

  // Session identifier (required, generated by storefront)
  sessionId: text('session_id').notNull().unique(),

  // Optional customer linking (set by storefront if they want customer records)
  customerId: uuid('customer_id').references(() => customersTable.id, {
    onDelete: 'set null'
  }),

  // Cart status
  status: cartStatusEnum('status').notNull().default('active'),

  // Calculated totals (updated via calculateTotals service method)
  subtotal: numeric('subtotal', { precision: 10, scale: 2 }).notNull().default('0'),
  discountTotal: numeric('discount_total', { precision: 10, scale: 2 }).notNull().default('0'),
  taxTotal: numeric('tax_total', { precision: 10, scale: 2 }).notNull().default('0'),
  shippingTotal: numeric('shipping_total', { precision: 10, scale: 2 }).notNull().default('0'),
  total: numeric('total', { precision: 10, scale: 2 }).notNull().default('0'),

  // Applied discount code
  discountCodeId: uuid('discount_code_id').references(() => discountCodesTable.id, {
    onDelete: 'set null'
  }),

  // Tracking timestamps
  expiresAt: timestamp('expires_at').notNull()
    .default(sql`NOW() + INTERVAL '30 days'`),
  lastActivityAt: timestamp('last_activity_at').notNull().defaultNow(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// Cart items table
export const cartItemsTable = pgTable('cart_items', {
  id: uuid('id').defaultRandom().primaryKey(),

  // Cart reference (cascade delete when cart is deleted)
  cartId: uuid('cart_id')
    .notNull()
    .references(() => cartsTable.id, { onDelete: 'cascade' }),

  // Product variant reference
  productVariantId: uuid('product_variant_id')
    .notNull()
    .references(() => productVariantsTable.id, { onDelete: 'cascade' }),

  // Quantity
  quantity: integer('quantity').notNull().default(1),

  // Price snapshot (captured at time of adding to cart)
  unitPrice: numeric('unit_price', { precision: 10, scale: 2 }).notNull(),

  // Timestamps
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// Cart relations
export const cartsRelations = relations(cartsTable, ({ one, many }) => ({
  customer: one(customersTable, {
    fields: [cartsTable.customerId],
    references: [customersTable.id],
  }),
  discountCode: one(discountCodesTable, {
    fields: [cartsTable.discountCodeId],
    references: [discountCodesTable.id],
  }),
  items: many(cartItemsTable),
}));

// Cart item relations
export const cartItemsRelations = relations(cartItemsTable, ({ one }) => ({
  cart: one(cartsTable, {
    fields: [cartItemsTable.cartId],
    references: [cartsTable.id],
  }),
  productVariant: one(productVariantsTable, {
    fields: [cartItemsTable.productVariantId],
    references: [productVariantsTable.id],
  }),
}));
